version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: account-service
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3307
      DB_NAME: passit_db
      DB_USER: passit_user
      DB_PASSWORD: passit_password
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - passit-network

networks:
  passit-network:
    external: true
    name: passit-network
