apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service-account.fullname" . }}-secret
  labels:
    {{- include "service-account.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-user: {{ .Values.database.user | quote }}
  db-password: {{ .Values.database.password | quote }}
  redis-password: {{ .Values.redis.password | quote }}
