apiVersion: v1
kind: ConfigMap
metadata:
  name: account-config
data:
  db.host: "postgres-service"
  db.port: "5432"
  db.name: "account_db"
  application.yml: |
    spring:
      application:
        name: account-service
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
