replicaCount: 2
image:
  repository: ghcr.io/cld4-t2-iamconan/service-account
  pullPolicy: IfNotPresent
  tag: "sha-23f50d3"

service:
  type: ClusterIP
  port: 80
  targetPort: 8081
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: account-service.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
<<<<<<< Updated upstream
  targetMemoryUtilizationPercentage: 80
=======
>>>>>>> Stashed changes
database:
  enabled: true
  host: passit-dev-aurora-cluster.cluster-cnqmcq6uwqa3.ap-northeast-2.rds.amazonaws.com
  port: 5432
  name: account_db
  user: postgres
  password: postgres
<<<<<<< Updated upstream
# Valkey 설정 (ElastiCache for Valkey)

redis:
  host: "passit-dev-valkey.q2tpkl.ng.0001.apn2.cache.amazonaws.com" # ElastiCache for Valkey 엔드포인트로 변경 필요
  port: 6379
  password: "" # ElastiCache 비밀번호가 있는 경우 설정
  ssl: true
=======
>>>>>>> Stashed changes
env:
  SPRING_PROFILES_ACTIVE: "production"
livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8081
  initialDelaySeconds: 30
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8081
  initialDelaySeconds: 20
  periodSeconds: 5
<<<<<<< Updated upstream
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::727646470302:role/passit-account-dev-irsa
=======
redis:
  host: passit-dev-valkey.q2tpkl.ng.0001.apn2.cache.amazonaws.com
>>>>>>> Stashed changes
s3:
  bucket: passit-dev-profile-images-bucket
